spring:
  application:
    name: TaskManagerApi
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager_db
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    include-stacktrace: never
